// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4X4nU7Tm5xtWjCZ3C9GA0tt8-5_984FE',
    appId: '1:181133299992:web:19b69a33664e9d3c160e6d',
    messagingSenderId: '181133299992',
    projectId: 'corvit-e2a35',
    authDomain: 'corvit-e2a35.firebaseapp.com',
    databaseURL: 'https://corvit-e2a35-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'corvit-e2a35.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8A5mXOVqEdRYmdfeeaSh4BO2fibxj64c',
    appId: '1:181133299992:android:8028b7a8facf2a81160e6d',
    messagingSenderId: '181133299992',
    projectId: 'corvit-e2a35',
    databaseURL: 'https://corvit-e2a35-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'corvit-e2a35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8rLCUZtR2jJ2aL3Z-ySxg9uT9iG0q16M',
    appId: '1:181133299992:ios:a3307dd14bbe212a160e6d',
    messagingSenderId: '181133299992',
    projectId: 'corvit-e2a35',
    databaseURL: 'https://corvit-e2a35-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'corvit-e2a35.appspot.com',
    iosBundleId: 'com.sarwar.corvit.corvit',
  );
}
